"""Localization utilities for handling UI text translation."""

import re


UI_TRANSLATIONS = {
    "PT-BR": {
        "WUWA LAB": "WUWA LAB",
        "ID da personagem:": "ID da personagem:",
        "Carregar Personagem / ID": "Carregar Personagem / ID",
        "Calcular Dano": "Calcular Dano",
        "Pronto": "Pronto",
        "Home": "Início",
        "Teams": "Times",
        "WUTHERING WAVES | DAMAGE SIMULATION": "WUTHERING WAVES | SIMULAÇÃO DE DANO",
        "Character Profile": "",
        "Signature Weapon": "Arma Característica",
        "KIT / ABILITIES": "KIT/HABILIDADES",
        "Echo build icons": "Ícones de Echo",
        "Character art": "Arte da personagem",
        "Weapon image": "Imagem da arma",
        "Echo image": "Imagem do Echo",
        "Loading...": "Carregando...",
        "No kit entries loaded.": "Nenhuma habilidade carregada.",
        "CRITICAL HIT BREAKDOWN": "Análise Detalhada de Acertos Críticos",
        "NORMAL / NON-CRIT": "NORMAL / NÃO CRÍTICO",
        "CRITICAL HIT": "ACERTO CRÍTICO",
        "EXPECTED AVERAGE": "MÉDIA ESPERADA",
        "CRIT RATE / CRIT DAMAGE": "TAXA CRÍTICA/ DANO CRÍTICO",
        "Relatório e DPS": "Relatório e DPS",
        "Team Buffs": "Bônus de Equipe",
        "Personal Buffs": "Bônus Pessoais",
        "Markers": "Marcadores",
        "Abilities": "Habilidades",
        "Echo": "Echo",
        "Basic Attack": "Ataque Básico",
        "Heavy Attack": "Ataque Pesado",
        "Resonance Skill": "Habilidade de Ressonância",
        "Resonance Liberation / Ultimate": "Liberação de Ressonância / Supremo",
        "Coordinated Attack": "Ataque Coordenado",
        "Forte Circuit": "Circuito Forte",
        "Intro Skill": "Habilidade de Entrada",
        "Outro Skill": "Habilidade de Saída",
        "Dodge Counter": "Contra-ataque de Esquiva",
        "Echo Skill": "Habilidade de Echo",
        "HIT DAMAGE BREAKDOWN": "DETALHAMENTO DO DANO POR ACERTO",
        "FULL ROTATION": "ROTAÇÃO COMPLETA",
        "Non-Crit Hit": "Acerto Não Crítico",
        "Crit Hit": "Acerto Crítico",
        "Average Expected Damage": "Dano Médio Esperado",
        "Full rotation damage": "Dano total da rotação",
        "Full rotation DPS": "DPS total da rotação",
        "Element": "Elemento",
        "Damage type": "Tipo de dano",
        "Team": "Time",
        "Team Buffs": "Bônus de equipe",
        "Personal Buffs": "Bônus pessoais",
        "Total additive bonus": "Bônus aditivo total",
        "Crit": "Crítico",
        "Target defense multiplier": "Multiplicador de defesa do alvo",
        "Elemental resistance multiplier": "Multiplicador de resistência elemental",
        "First ability base per hit": "Base da primeira habilidade por acerto",
        "First ability critical per hit": "Crítico da primeira habilidade por acerto",
        "Atributos base": "Atributos base",
        "HP Base": "HP Base",
        "Attack (ATK) Base": "Ataque (ATK) base",
        "Defense (DEF) Base": "Defesa (DEF) base",
        "Critical Rate (%)": "Taxa crítica (%)",
        "Critical Damage (%)": "Dano crítico (%)",
        "Combate e alvo": "Combate e alvo",
        "Scaling / multiplicador da skill (%)": "Escalonamento / multiplicador da habilidade (%)",
        "Defesa do inimigo (%)": "Defesa do inimigo (%)",
        "Redução de RES elemental (%)": "Redução de RES elemental (%)",
        "Quantidade de acertos": "Quantidade de acertos",
        "Casts por rotação": "Lançamentos por rotação",
        "Duração da rotação (s)": "Duração da rotação (s)",
        "Elemento e tipo de dano": "Elemento e tipo de dano",
        "Elemento": "Elemento",
        "Tipo": "Tipo",
        "Composição de time (DPS + 2 suportes)": "Composição de time (DPS + 2 suportes)",
        "DPS principal": "DPS principal",
        "Suporte 1": "Suporte 1",
        "Suporte 2": "Suporte 2",
        "Bônus global dos suportes (%)": "Bônus global dos suportes (%)",
        "Model: Scaling × ATK × additive bonuses × defense/resistance multipliers,": "Modelo: Scaling × ATK × bônus aditivos × multiplicadores de defesa/resistência,",
        "then expected crit using Critical Rate and Critical Damage.": "seguido do crítico esperado usando Taxa e Dano Crítico.",
        "Character ID": "ID da personagem",
        "Element": "Elemento",
        "Damage type": "Tipo de dano",
        "Team": "Time",
        "Crit": "Crítico",
        "Total additive bonus": "Bônus aditivo total",
        "First ability base per hit": "Base da primeira habilidade por acerto",
        "First ability critical per hit": "Crítico da primeira habilidade por acerto",
        "Golpe fallback": "Golpe fallback",
        "scaling": "escalonamento",
        "hit(s)": "acerto(s)",
        "cast(s)": "lançamento(s)",
    },
    "EN": {
        "ID da personagem:": "Character ID:",
        "Carregar Personagem / ID": "Load Character / ID",
        "Calcular Dano": "Calculate Damage",
        "Pronto": "Ready",
        "Relatório e DPS": "DPS Report",
        "Character ID": "Character ID",
        "Element": "Element",
        "Damage type": "Damage type",
        "Team": "Team",
        "Crit": "Crit",
        "Total additive bonus": "Total additive bonus",
        "First ability base per hit": "First ability base per hit",
        "First ability critical per hit": "First ability critical per hit",
        "Atributos base": "Base Attributes",
        "HP Base": "Base HP",
        "Attack (ATK) Base": "Base Attack (ATK)",
        "Defense (DEF) Base": "Base Defense (DEF)",
        "Critical Rate (%)": "Critical Rate (%)",
        "Critical Damage (%)": "Critical Damage (%)",
        "Combate e alvo": "Combat and Target",
        "Scaling / multiplicador da skill (%)": "Skill scaling / multiplier (%)",
        "Defesa do inimigo (%)": "Enemy defense (%)",
        "Redução de RES elemental (%)": "Elemental RES reduction (%)",
        "Quantidade de acertos": "Hit count",
        "Casts por rotação": "Casts per rotation",
        "Duração da rotação (s)": "Rotation duration (s)",
        "Elemento e tipo de dano": "Element and damage type",
        "Elemento": "Element",
        "Tipo": "Type",
        "Composição de time (DPS + 2 suportes)": "Team composition (DPS + 2 supports)",
        "DPS principal": "Main DPS",
        "Suporte 1": "Support 1",
        "Suporte 2": "Support 2",
        "Bônus global dos suportes (%)": "Global support bonus (%)",
        "Golpe fallback": "Fallback Hit",
        "scaling": "scaling",
        "hit(s)": "hit(s)",
        "cast(s)": "cast(s)",
    },
}


def translate_ui_text(text: str, language: str) -> str:
    """Translate UI labels while leaving character and weapon names untouched."""
    for key, portuguese in UI_TRANSLATIONS["PT-BR"].items():
        english = UI_TRANSLATIONS["EN"].get(key, key)
        if text in (key, portuguese, english):
            return UI_TRANSLATIONS[language].get(key, key)
    return text


def translate_content_text(text: str, language: str) -> str:
    """Translate manual kit titles and descriptions in both directions."""
    if language == "EN":
        replacements = {
            "Golpe fallback": "Fallback Hit",
            "Ataque Básico": "Basic Attack", "Ataque Pesado": "Heavy Attack",
            "Habilidade de Ressonância": "Resonance Skill", "Circuito Forte": "Forte Circuit",
            "Liberação de Ressonância": "Resonance Liberation", "Habilidade de Entrada": "Intro Skill",
            "Habilidade de Saída": "Outro Skill", "Ataque Coordenado": "Coordinated Attack",
            "Bônus de Ataque em Equipe": "Team Attack Bonus", "Bônus de Dano Pessoal": "Personal Damage Bonus",
            "Bônus de Equipe": "Team Buff", "Bônus Pessoal": "Personal Buff", "Marcador": "Marker",
            "Acumuladores / Stacks": "Stacks",
            "Descrição detalhada do ataque básico.": "Detailed Basic Attack description.",
            "Descrição da habilidade de ressonância.": "Resonance Skill description.",
            "Descrição do circuito forte.": "Forte Circuit description.",
            "Descrição da liberação de ressonância.": "Resonance Liberation description.",
            "Descrição da Xuanling...": "Xuanling description...", "Descrição da Yangyang...": "Yangyang description...",
            "Insira aqui a descrição detalhada do ataque básico da Cartethyia.": "Enter the detailed Cartethyia Basic Attack description here.",
            "Insira aqui a descrição detalhada da habilidade de ressonância.": "Enter the detailed Resonance Skill description here.",
            "Insira aqui a descrição detalhada do circuito forte.": "Enter the detailed Forte Circuit description here.",
            "Insira aqui a descrição detalhada da liberação de ressonância (Ult).": "Enter the detailed Resonance Liberation description here (Ultimate).",
            "Ataque Básico: Aalto dispara até 5 tiros consecutivos, causando Dano Aero. O 4º Ataque Básico espalha a Névoa para a frente, a qual permanece por 1,5s.": "Basic Attack Aalto fires up to 5 consecutive shots, dealing Aero DMG. Basic Attack 4 will spread the Mist forward, which lasts for 1.5s.",
        }
    else:
        replacements = {
            "Fallback Hit": "Golpe fallback",
            "Basic Attack": "Ataque Básico", "Heavy Attack": "Ataque Pesado",
            "Resonance Skill": "Habilidade de Ressonância", "Forte Circuit": "Circuito Forte",
            "Resonance Liberation": "Liberação de Ressonância", "Intro Skill": "Habilidade de Entrada",
            "Outro Skill": "Habilidade de Saída", "Coordinated Attack": "Ataque Coordenado",
            "Team Attack Bonus": "Bônus de Ataque em Equipe", "Personal Damage Bonus": "Bônus de Dano Pessoal",
            "Team Buff": "Bônus de Equipe", "Personal Buff": "Bônus Pessoal", "Marker": "Marcador",
            "Stacks": "Acumuladores / Stacks",
            "Detailed Basic Attack description.": "Descrição detalhada do ataque básico.",
            "Resonance Skill description.": "Descrição da habilidade de ressonância.",
            "Forte Circuit description.": "Descrição do circuito forte.",
            "Resonance Liberation description.": "Descrição da liberação de ressonância.",
            "Xuanling description...": "Descrição da Xuanling...", "Yangyang description...": "Descrição da Yangyang...",
            "Enter the detailed Cartethyia Basic Attack description here.": "Insira aqui a descrição detalhada do ataque básico da Cartethyia.",
            "Enter the detailed Resonance Skill description here.": "Insira aqui a descrição detalhada da habilidade de ressonância.",
            "Enter the detailed Forte Circuit description here.": "Insira aqui a descrição detalhada do circuito forte.",
            "Enter the detailed Resonance Liberation description here (Ultimate).": "Insira aqui a descrição detalhada da liberação de ressonância (Ult).",
            "Basic Attack Aalto fires up to 5 consecutive shots, dealing Aero DMG. Basic Attack 4 will spread the Mist forward, which lasts for 1.5s.": "Ataque Básico: Aalto dispara até 5 tiros consecutivos, causando Dano Aero. O 4º Ataque Básico espalha a Névoa para a frente, a qual permanece por 1,5s.",
            "Performs": "Executa", "performs": "executa", "Activates": "Ativa", "activates": "ativa",
            "Deals": "Causa", "deals": "causa", "Applies": "Aplica", "applies": "aplica",
            "Uses": "Usa", "uses": "usa", "Increases": "Aumenta", "increases": "aumenta",
            "Consumes": "Consome", "consumes": "consome", "Switches": "Alterna", "switches": "alterna",
            "builds": "acumula", "Builds": "Acumula", "and": "e", "while": "enquanto",
            "after": "após", "before": "antes de", "damage": "dano", "attack": "ataque",
            "attacks": "ataques", "skill": "habilidade", "skills": "habilidades",
            "effect": "efeito", "effects": "efeitos", "current state": "estado atual",
            "special attacks": "ataques especiais",
        }
    translated = text
    for source, target in sorted(replacements.items(), key=lambda item: len(item[0]), reverse=True):
        if language == "PT-BR" and source.isalpha():
            translated = re.sub(rf"\b{re.escape(source)}\b", target, translated)
        else:
            translated = translated.replace(source, target)
    return translate_ui_text(translated, language)
